# Site settings
title: Sexual Health Innovations Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

  The life, lessons, learning and discovery of a startup nonprofit.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SHInnovations
github_username:  #SexualHealthInnovations

# Build settings
markdown: kramdown
